DROP TABLE IF EXISTS badges CASCADE;

CREATE TABLE badges (
  id SERIAL PRIMARY KEY NOT NULL,

  badge_id INTEGER REFERENCES badges (id) ON DELETE CASCADE,
  users_id INTEGER REFERENCES users (id) ON DELETE CASCADE
);