
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,

  name VARCHAR(255) NOT NULL,
  treats INTEGER NOT NULL DEFAULT 1,
  password VARCHAR(255) NOT NULL,
  profile_picture VARCHAR(255) NOT NULL,
  bio VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  address VARCHAR(255) NOT NULL
);
